language: python
dist: xenial
# ========== LINUX ==========
python:
  - "3.7"
  - "3.8"
branches:
  only:
  - master

matrix:
  include:      
    # ========== WINDOWS ==========
    - name: "Python 3.7.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        # -----------------------------------------------------
        - export ANACONDA_PATH=$HOME/Anaconda3;
        # - export ANACONDA_PATH_WIN=`cygpath --windows $ANACONDA_PATH`;
        - choco install anaconda3 --params='/JustMe /AddToPath /D:'"$ANACONDA_PATH";
        # - wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Windows-x86_64.exe -0 conda.exe
        - export ANACONDA_LIB_BIN_PATH=$ANACONDA_PATH/Library/bin;
        - export PATH="$ANACONDA_PATH:$ANACONDA_LIB_BIN_PATH:$PATH";
        - source $ANACONDA_PATH/etc/profile.d/conda.sh;
        - hash -r;
        - conda config --set always_yes yes --set changeps1 no;
        - conda update -q conda;
        - conda info -a
        # -----------------------------------------------------
        - conda env create -n sira-env -f ./installation/environment_${TRAVIS_OS_NAME}.yml;
        - conda activate sira-env
        - conda list
        # -----------------------------------------------------
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        # -----------------------------------------------------
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - sudo apt-get install -y --no-install-recommends apt-utils
  - sudo apt-get install -y  $(awk '{print $1}' ./installation/packagelist_linux.txt)
  # - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
  - sudo apt-get install -y ttf-mscorefonts-installer
  - wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh
  - bash /tmp/Anaconda3*.sh -b -p $HOME/anaconda3
  - export PATH="$HOME/anaconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n sira_env python=$TRAVIS_PYTHON_VERSION
  - eval "$(conda shell.bash hook)"
  - conda activate sira_env
  - conda env list
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -r ./installation/requirements.txt
script:
  - python3 -m pytest
after_success:
  - codecov
