language: python
os: linux
dist: xenial

# ======================== LINUX ========================
python:
  - 3.7
  - 3.8

branches:
  only:
  - master

jobs:
  include:      
    # ======================== WINDOWS ========================
    - name: "Python 3.8.6 on Windows"
      os: windows        # Windows 10.0.17134 N/A Build 17134
      language: shell    # 'language: python' is an error on Travis CI Windows
      env: PATH=/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3//Library/bin:$PATH
      before_install:
        # ---------------------------------------------------------------------
        # Set up path variables for Chocolatey installation of miniconda
        - export CONDA_PATH=/c/Tools/miniconda3
        - export CONDA_BIN=$CONDA_PATH/Library/bin:$CONDA_PATH/condabin
        - export CONDA_SCRIPTS=$CONDA_PATH/Scripts
        - export DEV_ENV="sira_env"
      install:
        # ---------------------------------------------------------------------
        # Install Anaconda and configure conda
        - choco install miniconda3 --params="'/JustMe /AddToPath'"
        - export PATH=$CONDA_PATH:$CONDA_BIN:$CONDA_SCRIPTS:$PATH
        - echo $PATH
        - choco install graphviz
        - source "$CONDA_PATH/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        # ---------------------------------------------------------------------
        # Create and activate the environment
        - conda create -n $DEV_ENV python=$TRAVIS_PYTHON_VERSION
        - source "$CONDA_PATH/Scripts/activate"
        - conda activate $DEV_ENV
        - python -m pip install --upgrade pip
        - pip --use-feature=2020-resolver install -r ./installation/requirements_windows.txt
        - conda install -c conda-forge freetype python-igraph==0.8.3
        - conda install -c alubbock pygraphviz
        - conda --version ; python --version ; pip --version
        - conda list
        # ---------------------------------------------------------------------
        # Need to register Graphviz plugins before they can be used: 
        # https://stackoverflow.com/a/62549025
        - dot -c
        # ---------------------------------------------------------------------

install:
  - sudo apt-get install -y --no-install-recommends apt-utils
  - sudo apt-get install -y  $(awk '{print $1}' ./installation/packagelist_linux.txt)
  - sudo apt-get install -y ttf-mscorefonts-installer
  - wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh
  - bash /tmp/Anaconda3*.sh -b -p $HOME/anaconda3
  - export PATH="$HOME/anaconda3/bin:$PATH"
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n sira_env python=$TRAVIS_PYTHON_VERSION
  - eval "$(conda shell.bash hook)"
  - conda activate sira_env
  - conda install graphviz pygraphviz -c conda-forge
  - conda install libtiff
  - conda install libpng
  - conda env list
  - python --version
  - pip install -U pip
  - pip install --upgrade pytest
  - pip install -r ./installation/requirements.txt

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      python3 -m pytest;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      python -m pytest;
    fi;

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
