name: sira_env
channels:
    - conda-forge
    - defaults
    - alubbock
dependencies:
    - python=3.7.6
    - pip=20.2.3
    - awscli=1.18.157
    - brewer2mpl=1.4
    - colorama=0.4.3
    - configparser=5.0.1
    - coverage=5.3
    - freetype=2.10.3
    - ipython=7.18.1
    - jupyterlab=2.2.8
    - latexcodec=2.0.1
    - libpng=1.6.37
    - libtiff=4.1.0
    - lmfit=1.0.1
    - matplotlib=3.3.2
    - netcdf4=1.5.4
    - networkx=2.5
    - notebook=6.1.4
    - numpy=1.19.2
    - openpyxl=3.0.5
    - pandas=1.1.3
    - parmap=1.5.2
    - pillow=7.2.0
    - pycairo=1.20.0
    - pycparser=2.20
    - pygments=2.7.1
    - pylint=2.6.0
    - pytest=6.1.1
    - pytest-cov=2.10.1
    - codecov=2.1.10
    - python-igraph=0.8.2
    - requests=2.24.0
    - s3transfer=0.3.3
    - seaborn=0.11.0
    - scikit-image=0.17.2
    - scikit-learn=0.23.2
    - scipy=1.5.2
    - sqlite=3.33.0
    - sqlalchemy=1.3.19
    - xlrd=1.2.0
    - alubbock::graphviz=2.41
    - free::pydot-ng=1.0.0
    - alubbock::pygraphviz=1.5
    - python-graphviz=0.14.2
    - pip:
        - actdiag==2.0.0
        - alabaster==0.7.12
        - blockdiag==2.0.1
        - docutils==0.16
        - pybtex==0.22.2
        - pybtex-docutils==0.2.2
        - seqdiag==2.0.0
        - sphinx==3.2.1
        - sphinx-rtd-theme==0.5.0
        - sphinxcontrib-actdiag==2.0.0
        - sphinxcontrib-bibtex==1.0.0
        - sphinxcontrib-blockdiag==2.0.0
        - sphinxcontrib-jsmath==1.0.1
        - sphinxcontrib-seqdiag==2.0.0
        - sphinxcontrib-websupport==1.2.4
