name: sifra_devenv
channels:
    - marufr
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - brewer2mpl
    - colorama
    - coloredlogs
    - configparser
    - graphviz
    - ipython
    - matplotlib
    - netcdf4
    - networkx
    - numpy
    - pandas
    - pycairo
    - pygraphviz
    - python-igraph==0.7.1.post6
    - scipy
    - scikit-learn
    - seaborn
    - six
    - sqlalchemy
    - xlrd
    - zlib
    - pip:
        - actdiag
        - blockdiag
        - funcparserlib
        - lmfit
        - markupsafe
        - nwdiag
        - parmap
        - pexpect
        - pydot
        - pybtex
        - pybtex-docutils
        - pygments
        - pyparsing
        - seqdiag
        - sphinx
        - sphinx-rtd-theme
        - sphinxcontrib-actdiag
        - sphinxcontrib-bibtex
        - sphinxcontrib-blockdiag
        - sphinxcontrib-exceltable
        - sphinxcontrib-nwdiag
        - sphinxcontrib-seqdiag
        - sphinxcontrib-websupport
        - webcolors
recovery_95percentile