name: sira_env
channels:
    - conda-forge
    - defaults
    - alubbock
dependencies:
    - python=3.7.6
    - pip=20.1.1
    - awscli
    - brewer2mpl
    - colorama
    - configparser
    - coverage
    - freetype
    - graphviz
    - ipython
    - jupyterlab
    - latexcodec
    - libpng
    - libtiff
    - lmfit
    - matplotlib
    - netcdf4
    - networkx
    - notebook
    - numpy
    - openpyxl
    - pandas
    - parmap
    - pillow
    - pycairo
    - pycparser
    - pygments
    - pylint
    - pytest
    - pytest-cov
    - python-igraph=0.8.2
    - pygraphviz
    - requests
    - s3transfer
    - seaborn
    - scikit-image
    - scikit-learn
    - scipy>=1.5.2
    - sqlite
    - sqlalchemy
    - xlrd
    - pip:
        - alabaster
        - actdiag
        - blockdiag
        - docutils
        - pybtex
        - pybtex-docutils
        - seqdiag
        - sphinx
        - sphinx-rtd-theme
        - sphinxcontrib-actdiag
        - sphinxcontrib-bibtex
        - sphinxcontrib-blockdiag
        - sphinxcontrib-jsmath
        - sphinxcontrib-seqdiag
        - sphinxcontrib-websupport
